version: '3'
services:
  php-apache:
    image: php:apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    container_name: db_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1212312121
      MYSQL_DATABASE: se_db
      MYSQL_USER: web
      MYSQL_PASSWORD: web1234
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
